// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5FGSK0NGVVSiF-4n5njB3mayi_xUtJy8',
    appId: '1:3834777118:web:b2cee41c3ec2f76e88680f',
    messagingSenderId: '3834777118',
    projectId: 'jokesappproject-6ef5e',
    authDomain: 'jokesappproject-6ef5e.firebaseapp.com',
    storageBucket: 'jokesappproject-6ef5e.firebasestorage.app',
    measurementId: 'G-P2SKTRM08L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrB36B6juXV8nVf1wi__SFbBRnY0k85Ho',
    appId: '1:3834777118:android:aff9065d102b949e88680f',
    messagingSenderId: '3834777118',
    projectId: 'jokesappproject-6ef5e',
    storageBucket: 'jokesappproject-6ef5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWGoNwsG1qr7uJkBkVfmpGYVWoQZMYA0g',
    appId: '1:3834777118:ios:65298cbe9f154a5a88680f',
    messagingSenderId: '3834777118',
    projectId: 'jokesappproject-6ef5e',
    storageBucket: 'jokesappproject-6ef5e.firebasestorage.app',
    iosBundleId: 'com.example.randomJokesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWGoNwsG1qr7uJkBkVfmpGYVWoQZMYA0g',
    appId: '1:3834777118:ios:65298cbe9f154a5a88680f',
    messagingSenderId: '3834777118',
    projectId: 'jokesappproject-6ef5e',
    storageBucket: 'jokesappproject-6ef5e.firebasestorage.app',
    iosBundleId: 'com.example.randomJokesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5FGSK0NGVVSiF-4n5njB3mayi_xUtJy8',
    appId: '1:3834777118:web:6f85dfb45ca034dc88680f',
    messagingSenderId: '3834777118',
    projectId: 'jokesappproject-6ef5e',
    authDomain: 'jokesappproject-6ef5e.firebaseapp.com',
    storageBucket: 'jokesappproject-6ef5e.firebasestorage.app',
    measurementId: 'G-4YF4Y1RL5Z',
  );
}
